// All type resolutions passed successfully!


//----------------------------------------------------------

/* --- Raw Reflection Data (Pretty Print) ---

=============================================

apic_Exports: mysimplelib

Description: Example exports with full documentation support

=== apic_Structs (6) ===
Vec2I: 
apic_Fields (2):
  x: int (X coordinate)
  y: int (Y coordinate)

Vec3I: 3D integer vector
apic_Fields (3):
  x: int ()
  y: int ()
  z: int ()

Calculator: 
apic_Fields (2):
  adder: Adder ()
  value: float ()

Node: 
apic_Fields (2):
  value: int ()
  next: struct Node* ()

Buffer: 
apic_Fields (2):
  data: char[256] ()
  size: int (Current buffer size)

Matrix: 
apic_Fields (3):
  values: float[16] ()
  rows: int (Matrix dimensions)
  cols: int ()

=== apic_Unions (1) ===
Number: 
apic_Fields (2):
  i: int (Integer storage)
  f: float (Floating point storage)

=== apic_Functions (2) ===
add_mixed: Adds int and float
Returns: int
apic_Args (2):
  a: int ()
  b: float ()

my_fn: 
Returns: Vec2I
apic_Args (2):
  x: int ()
  y: int ()

=== apic_FuncPtrs (1) ===
Adder: Adds int and float
Returns: int
apic_Args (2):
  a: int ()
  b: float ()

=== apic_Enums (1) ===
COLOR: Basic colors
Entries (3):
  RED = 0 (red, Primary color)
  GREEN = 1 (green, Secondary color)
  BLUE = 2 (blue, Primary color)

=== apic_Aliases (1) ===
Byte = unsigned char (Single byte type)

=============================================


--- End Raw Reflection --- */


// --- Generating Public C Header ---
//----------------------------------------------------------

// =============================================
// Public API Header: mysimplelib
// Description: Example exports with full documentation support
// Generated by APIC reflection system
// =============================================

#ifndef mysimplelib_PUBLIC_H
#define mysimplelib_PUBLIC_H

#include <stdint.h> // Standard types
#include <stddef.h> // For size_t
#include <stdbool.h> // For bool

// =============== Typedefs / Aliases ===============
// Single byte type
typedef unsigned char Byte;

// =================== Enums ===================/
// Basic colors
typedef enum COLOR {
    RED = 0, // red, Primary color
    GREEN = 1, // green, Secondary color
    BLUE = 2 // blue, Primary color
} COLOR;

// ============ Forward Declarations ============/
typedef struct Vec2I Vec2I;
typedef struct Vec3I Vec3I;
typedef struct Calculator Calculator;
typedef struct Node Node;
typedef struct Buffer Buffer;
typedef struct Matrix Matrix;

// ============ Function Pointer Types ============/
// Adds int and float
typedef int (*Adder)(int a, float b);

// ================ Structures ================/
struct Vec2I {
    int x; // X coordinate
    int y; // Y coordinate
};

// 3D integer vector
struct Vec3I {
    int x;
    int y;
    int z;
};

struct Calculator {
    Adder adder;
    float value;
};

struct Node {
    int value;
    struct Node* next;
};

struct Buffer {
    char data[256];
    int size; // Current buffer size
};

struct Matrix {
    float values[16];
    int rows; // Matrix dimensions
    int cols;
};

// ================== Unions ==================/
typedef union Number {
    int i; // Integer storage
    float f; // Floating point storage
} Number;

// ================ Functions ================/
// Adds int and float
int add_mixed(int a, float b);

struct Vec2I my_fn(int x, int y);

#endif // mysimplelib_PUBLIC_H

// --- Generating Lua 5.1 Bindings to test/output/basic_lua_bindings.c ---
// Lua Bindings generation done.
