// ==========================================================
// Lua 5.1 Bindings for mysimplelib
// Generated by APIC reflection system (Light Userdata Handle Version)
// ==========================================================

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>

#include "basic_generated.h"

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
//         HANDLE TABLE METATABLE DEFINITIONS
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

// --- Metatable for struct Vec2I Handle (apic.meta.mysimplelib.Vec2I) ---

// Helper to safely get C pointer from handle table
static struct Vec2I* mysimplelib_Vec2I___apic_get_ptr(lua_State *L, const char* meta_name) {
    // Assumes arg 1 is the handle table already validated
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) {
        lua_pop(L, 1);
        luaL_error(L, "Handle table for %s missing or invalid '_id' field", meta_name);
        return NULL; // Should not be reached
    }
    struct Vec2I* ptr = (struct Vec2I*)lua_touserdata(L, -1);
    lua_pop(L, 1);
    if (ptr == NULL) {
        luaL_error(L, "Handle table for %s '_id' points to NULL", meta_name);
        // return NULL; // Error throws
    }
    return ptr;
}

static int mysimplelib_Vec2I__index(lua_State *L) {
    // Arg 1: handle table, Arg 2: key
    const char* key = luaL_checkstring(L, 2);
    struct Vec2I* self = mysimplelib_Vec2I___apic_get_ptr(L, "apic.meta.mysimplelib.Vec2I"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "x") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->x));
        return 1;
    }
    if (strcmp(key, "y") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->y));
        return 1;
    }

    // Fallback: Check for methods in metatable
    lua_getmetatable(L, 1);
    lua_pushvalue(L, 2);
    lua_rawget(L, -2);
    lua_remove(L, -2);
    if (!lua_isnil(L, -1)) {
        return 1; // Return method
    } else {
        return luaL_error(L, "No such field or method '%s' in struct %s handle", key, "Vec2I", "Vec2I");
    }
}

static int mysimplelib_Vec2I__newindex(lua_State *L) {
    // Arg 1: handle table, Arg 2: key, Arg 3: value
    const char* key = luaL_checkstring(L, 2);
    struct Vec2I* self = mysimplelib_Vec2I___apic_get_ptr(L, "apic.meta.mysimplelib.Vec2I"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "x") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->x = new_value_x;
        return 0; // Assignment successful
    }
    if (strcmp(key, "y") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->y = new_value_y;
        return 0; // Assignment successful
    }

    return luaL_error(L, "No such field '%s' in struct %s handle to assign to", key, "Vec2I", "Vec2I");
}

static int mysimplelib_Vec2I__tostring(lua_State *L) {
    // Arg 1: handle table
    struct Vec2I* self = mysimplelib_Vec2I___apic_get_ptr(L, "apic.meta.mysimplelib.Vec2I"); // Get C pointer
    if (!self) { lua_pushstring(L, "Invalid handle"); return 1; } // Handle NULL case gracefully?
    lua_pushfstring(L, "struct Vec2I Handle: %p", (void*)self);
    return 1;
}

// User must define Vec2I_release( struct Vec2I* obj ) if GC cleanup is needed.
// Example: void Vec2I_release(struct Vec2I* obj) { printf("Releasing Vec2I %p\n", (void*)obj); free(obj); }
// extern void Vec2I_release(struct Vec2I* obj); // Weak link? Or just call and let linker find it.

static int mysimplelib_Vec2I__gc(lua_State *L) {
    // Arg 1: handle table being collected
    printf("GC triggered for Vec2I handle.\n"); // Debug
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) == LUA_TLIGHTUSERDATA) {
        struct Vec2I* ptr = (struct Vec2I*)lua_touserdata(L, -1);
        lua_pop(L, 1);
        if (ptr != NULL) {
            printf("  >> GC: C Pointer is %p\n", (void*)ptr);//mg:Vec2I
            // --- Call user-defined C cleanup function --- 
            // Vec2I_release(ptr); // Uncomment this line or provide your cleanup call 
            printf("  >> GC: Object cleanup function 'Vec2I_release' should be called here.\n");
            // Important: Set handle's _id to NULL after cleanup to prevent double-free/use-after-free
            lua_pushnil(L);
            lua_setfield(L, 1, "_id");
        } else {
             printf("  >> GC: C Pointer was NULL.\n");
        }
    } else {
        printf("  >> GC: Handle table '_id' not lightuserdata!\n");
        lua_pop(L, 1);
    }
    return 0;
}

static const luaL_Reg mysimplelib_Vec2I_meta[] = {
    {"__index", mysimplelib_Vec2I__index},
    {"__newindex", mysimplelib_Vec2I__newindex},
    {"__tostring", mysimplelib_Vec2I__tostring},
    {"__gc", mysimplelib_Vec2I__gc}, // Add GC hook
    {NULL, NULL}
};

// --- End Metatable for struct Vec2I Handle ---

// --- Metatable for struct Vec3I Handle (apic.meta.mysimplelib.Vec3I) ---

// Helper to safely get C pointer from handle table
static struct Vec3I* mysimplelib_Vec3I___apic_get_ptr(lua_State *L, const char* meta_name) {
    // Assumes arg 1 is the handle table already validated
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) {
        lua_pop(L, 1);
        luaL_error(L, "Handle table for %s missing or invalid '_id' field", meta_name);
        return NULL; // Should not be reached
    }
    struct Vec3I* ptr = (struct Vec3I*)lua_touserdata(L, -1);
    lua_pop(L, 1);
    if (ptr == NULL) {
        luaL_error(L, "Handle table for %s '_id' points to NULL", meta_name);
        // return NULL; // Error throws
    }
    return ptr;
}

static int mysimplelib_Vec3I__index(lua_State *L) {
    // Arg 1: handle table, Arg 2: key
    const char* key = luaL_checkstring(L, 2);
    struct Vec3I* self = mysimplelib_Vec3I___apic_get_ptr(L, "apic.meta.mysimplelib.Vec3I"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "x") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->x));
        return 1;
    }
    if (strcmp(key, "y") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->y));
        return 1;
    }
    if (strcmp(key, "z") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->z));
        return 1;
    }

    // Fallback: Check for methods in metatable
    lua_getmetatable(L, 1);
    lua_pushvalue(L, 2);
    lua_rawget(L, -2);
    lua_remove(L, -2);
    if (!lua_isnil(L, -1)) {
        return 1; // Return method
    } else {
        return luaL_error(L, "No such field or method '%s' in struct %s handle", key, "Vec3I", "Vec3I");
    }
}

static int mysimplelib_Vec3I__newindex(lua_State *L) {
    // Arg 1: handle table, Arg 2: key, Arg 3: value
    const char* key = luaL_checkstring(L, 2);
    struct Vec3I* self = mysimplelib_Vec3I___apic_get_ptr(L, "apic.meta.mysimplelib.Vec3I"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "x") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->x = new_value_x;
        return 0; // Assignment successful
    }
    if (strcmp(key, "y") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->y = new_value_y;
        return 0; // Assignment successful
    }
    if (strcmp(key, "z") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->z = new_value_z;
        return 0; // Assignment successful
    }

    return luaL_error(L, "No such field '%s' in struct %s handle to assign to", key, "Vec3I", "Vec3I");
}

static int mysimplelib_Vec3I__tostring(lua_State *L) {
    // Arg 1: handle table
    struct Vec3I* self = mysimplelib_Vec3I___apic_get_ptr(L, "apic.meta.mysimplelib.Vec3I"); // Get C pointer
    if (!self) { lua_pushstring(L, "Invalid handle"); return 1; } // Handle NULL case gracefully?
    lua_pushfstring(L, "struct Vec3I Handle: %p", (void*)self);
    return 1;
}

// User must define Vec3I_release( struct Vec3I* obj ) if GC cleanup is needed.
// Example: void Vec3I_release(struct Vec3I* obj) { printf("Releasing Vec3I %p\n", (void*)obj); free(obj); }
// extern void Vec3I_release(struct Vec3I* obj); // Weak link? Or just call and let linker find it.

static int mysimplelib_Vec3I__gc(lua_State *L) {
    // Arg 1: handle table being collected
    printf("GC triggered for Vec3I handle.\n"); // Debug
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) == LUA_TLIGHTUSERDATA) {
        struct Vec3I* ptr = (struct Vec3I*)lua_touserdata(L, -1);
        lua_pop(L, 1);
        if (ptr != NULL) {
            printf("  >> GC: C Pointer is %p\n", (void*)ptr);//mg:Vec3I
            // --- Call user-defined C cleanup function --- 
            // Vec3I_release(ptr); // Uncomment this line or provide your cleanup call 
            printf("  >> GC: Object cleanup function 'Vec3I_release' should be called here.\n");
            // Important: Set handle's _id to NULL after cleanup to prevent double-free/use-after-free
            lua_pushnil(L);
            lua_setfield(L, 1, "_id");
        } else {
             printf("  >> GC: C Pointer was NULL.\n");
        }
    } else {
        printf("  >> GC: Handle table '_id' not lightuserdata!\n");
        lua_pop(L, 1);
    }
    return 0;
}

static const luaL_Reg mysimplelib_Vec3I_meta[] = {
    {"__index", mysimplelib_Vec3I__index},
    {"__newindex", mysimplelib_Vec3I__newindex},
    {"__tostring", mysimplelib_Vec3I__tostring},
    {"__gc", mysimplelib_Vec3I__gc}, // Add GC hook
    {NULL, NULL}
};

// --- End Metatable for struct Vec3I Handle ---

// --- Metatable for struct Calculator Handle (apic.meta.mysimplelib.Calculator) ---

// Helper to safely get C pointer from handle table
static struct Calculator* mysimplelib_Calculator___apic_get_ptr(lua_State *L, const char* meta_name) {
    // Assumes arg 1 is the handle table already validated
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) {
        lua_pop(L, 1);
        luaL_error(L, "Handle table for %s missing or invalid '_id' field", meta_name);
        return NULL; // Should not be reached
    }
    struct Calculator* ptr = (struct Calculator*)lua_touserdata(L, -1);
    lua_pop(L, 1);
    if (ptr == NULL) {
        luaL_error(L, "Handle table for %s '_id' points to NULL", meta_name);
        // return NULL; // Error throws
    }
    return ptr;
}

static int mysimplelib_Calculator__index(lua_State *L) {
    // Arg 1: handle table, Arg 2: key
    const char* key = luaL_checkstring(L, 2);
    struct Calculator* self = mysimplelib_Calculator___apic_get_ptr(L, "apic.meta.mysimplelib.Calculator"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "adder") == 0) {
    /* Unsupported type Adder */ lua_pushnil(L);
        return 1;
    }
    if (strcmp(key, "value") == 0) {
    lua_pushnumber(L, (lua_Number)(self->value));
        return 1;
    }

    // Fallback: Check for methods in metatable
    lua_getmetatable(L, 1);
    lua_pushvalue(L, 2);
    lua_rawget(L, -2);
    lua_remove(L, -2);
    if (!lua_isnil(L, -1)) {
        return 1; // Return method
    } else {
        return luaL_error(L, "No such field or method '%s' in struct %s handle", key, "Calculator", "Calculator");
    }
}

static int mysimplelib_Calculator__newindex(lua_State *L) {
    // Arg 1: handle table, Arg 2: key, Arg 3: value
    const char* key = luaL_checkstring(L, 2);
    struct Calculator* self = mysimplelib_Calculator___apic_get_ptr(L, "apic.meta.mysimplelib.Calculator"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "adder") == 0) {
    luaL_error(L, "Unsupported type '%s' (kind %d) for argument %d in %s", "Adder", 8, 3, "__newindex");
        self->adder = new_value_adder;
        return 0; // Assignment successful
    }
    if (strcmp(key, "value") == 0) {
    float new_value_value = (float)luaL_checknumber(L, 3);
        self->value = new_value_value;
        return 0; // Assignment successful
    }

    return luaL_error(L, "No such field '%s' in struct %s handle to assign to", key, "Calculator", "Calculator");
}

static int mysimplelib_Calculator__tostring(lua_State *L) {
    // Arg 1: handle table
    struct Calculator* self = mysimplelib_Calculator___apic_get_ptr(L, "apic.meta.mysimplelib.Calculator"); // Get C pointer
    if (!self) { lua_pushstring(L, "Invalid handle"); return 1; } // Handle NULL case gracefully?
    lua_pushfstring(L, "struct Calculator Handle: %p", (void*)self);
    return 1;
}

// User must define Calculator_release( struct Calculator* obj ) if GC cleanup is needed.
// Example: void Calculator_release(struct Calculator* obj) { printf("Releasing Calculator %p\n", (void*)obj); free(obj); }
// extern void Calculator_release(struct Calculator* obj); // Weak link? Or just call and let linker find it.

static int mysimplelib_Calculator__gc(lua_State *L) {
    // Arg 1: handle table being collected
    printf("GC triggered for Calculator handle.\n"); // Debug
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) == LUA_TLIGHTUSERDATA) {
        struct Calculator* ptr = (struct Calculator*)lua_touserdata(L, -1);
        lua_pop(L, 1);
        if (ptr != NULL) {
            printf("  >> GC: C Pointer is %p\n", (void*)ptr);//mg:Calculator
            // --- Call user-defined C cleanup function --- 
            // Calculator_release(ptr); // Uncomment this line or provide your cleanup call 
            printf("  >> GC: Object cleanup function 'Calculator_release' should be called here.\n");
            // Important: Set handle's _id to NULL after cleanup to prevent double-free/use-after-free
            lua_pushnil(L);
            lua_setfield(L, 1, "_id");
        } else {
             printf("  >> GC: C Pointer was NULL.\n");
        }
    } else {
        printf("  >> GC: Handle table '_id' not lightuserdata!\n");
        lua_pop(L, 1);
    }
    return 0;
}

static const luaL_Reg mysimplelib_Calculator_meta[] = {
    {"__index", mysimplelib_Calculator__index},
    {"__newindex", mysimplelib_Calculator__newindex},
    {"__tostring", mysimplelib_Calculator__tostring},
    {"__gc", mysimplelib_Calculator__gc}, // Add GC hook
    {NULL, NULL}
};

// --- End Metatable for struct Calculator Handle ---

// --- Metatable for struct Node Handle (apic.meta.mysimplelib.Node) ---

// Helper to safely get C pointer from handle table
static struct Node* mysimplelib_Node___apic_get_ptr(lua_State *L, const char* meta_name) {
    // Assumes arg 1 is the handle table already validated
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) {
        lua_pop(L, 1);
        luaL_error(L, "Handle table for %s missing or invalid '_id' field", meta_name);
        return NULL; // Should not be reached
    }
    struct Node* ptr = (struct Node*)lua_touserdata(L, -1);
    lua_pop(L, 1);
    if (ptr == NULL) {
        luaL_error(L, "Handle table for %s '_id' points to NULL", meta_name);
        // return NULL; // Error throws
    }
    return ptr;
}

static int mysimplelib_Node__index(lua_State *L) {
    // Arg 1: handle table, Arg 2: key
    const char* key = luaL_checkstring(L, 2);
    struct Node* self = mysimplelib_Node___apic_get_ptr(L, "apic.meta.mysimplelib.Node"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "value") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->value));
        return 1;
    }
    if (strcmp(key, "next") == 0) {
    // Push struct Node* handle
    if (self->next == NULL) {
        lua_pushnil(L);
    } else {
        lua_newtable(L); // Stack: handle_table
        lua_pushlightuserdata(L, (void*)(self->next)); // Stack: handle_table, lightud
        lua_setfield(L, -2, "_id"); // Stack: handle_table
        luaL_getmetatable(L, "apic.meta.mysimplelib.Node"); // Stack: handle_table, meta
        if (lua_isnil(L, -1)) { /* Meta not found! */ lua_pop(L, 2); lua_pushnil(L); } else { lua_setmetatable(L, -2); }
    }
        return 1;
    }

    // Fallback: Check for methods in metatable
    lua_getmetatable(L, 1);
    lua_pushvalue(L, 2);
    lua_rawget(L, -2);
    lua_remove(L, -2);
    if (!lua_isnil(L, -1)) {
        return 1; // Return method
    } else {
        return luaL_error(L, "No such field or method '%s' in struct %s handle", key, "Node", "Node");
    }
}

static int mysimplelib_Node__newindex(lua_State *L) {
    // Arg 1: handle table, Arg 2: key, Arg 3: value
    const char* key = luaL_checkstring(L, 2);
    struct Node* self = mysimplelib_Node___apic_get_ptr(L, "apic.meta.mysimplelib.Node"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "value") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->value = new_value_value;
        return 0; // Assignment successful
    }
    if (strcmp(key, "next") == 0) {
    // Check for handle table for struct Node*
    if (lua_type(L, 3) != LUA_TTABLE) { luaL_argerror(L, 3, "Expected handle table for struct Node"); }
    if (!lua_getmetatable(L, 3)) { luaL_argerror(L, 3, "Handle table missing metatable"); }
    luaL_getmetatable(L, "apic.meta.mysimplelib.Node"); // Stack: ..., handle_table, meta, expected_meta
    if (!lua_rawequal(L, -1, -2)) { lua_pop(L, 2); luaL_argerror(L, 3, "Incorrect handle type (expected apic.meta.mysimplelib.Node)"); }
    lua_pop(L, 2); // Pop both metatables
    lua_getfield(L, 3, "_id"); // Stack: ..., handle_table, lightuserdata
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) { lua_pop(L, 1); luaL_argerror(L, 3, "Handle table '_id' field is not lightuserdata"); }
    struct Node* new_value_next = (struct Node*)lua_touserdata(L, -1);
    lua_pop(L, 1); // Pop lightuserdata
        self->next = new_value_next;
        return 0; // Assignment successful
    }

    return luaL_error(L, "No such field '%s' in struct %s handle to assign to", key, "Node", "Node");
}

static int mysimplelib_Node__tostring(lua_State *L) {
    // Arg 1: handle table
    struct Node* self = mysimplelib_Node___apic_get_ptr(L, "apic.meta.mysimplelib.Node"); // Get C pointer
    if (!self) { lua_pushstring(L, "Invalid handle"); return 1; } // Handle NULL case gracefully?
    lua_pushfstring(L, "struct Node Handle: %p", (void*)self);
    return 1;
}

// User must define Node_release( struct Node* obj ) if GC cleanup is needed.
// Example: void Node_release(struct Node* obj) { printf("Releasing Node %p\n", (void*)obj); free(obj); }
// extern void Node_release(struct Node* obj); // Weak link? Or just call and let linker find it.

static int mysimplelib_Node__gc(lua_State *L) {
    // Arg 1: handle table being collected
    printf("GC triggered for Node handle.\n"); // Debug
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) == LUA_TLIGHTUSERDATA) {
        struct Node* ptr = (struct Node*)lua_touserdata(L, -1);
        lua_pop(L, 1);
        if (ptr != NULL) {
            printf("  >> GC: C Pointer is %p\n", (void*)ptr);//mg:Node
            // --- Call user-defined C cleanup function --- 
            // Node_release(ptr); // Uncomment this line or provide your cleanup call 
            printf("  >> GC: Object cleanup function 'Node_release' should be called here.\n");
            // Important: Set handle's _id to NULL after cleanup to prevent double-free/use-after-free
            lua_pushnil(L);
            lua_setfield(L, 1, "_id");
        } else {
             printf("  >> GC: C Pointer was NULL.\n");
        }
    } else {
        printf("  >> GC: Handle table '_id' not lightuserdata!\n");
        lua_pop(L, 1);
    }
    return 0;
}

static const luaL_Reg mysimplelib_Node_meta[] = {
    {"__index", mysimplelib_Node__index},
    {"__newindex", mysimplelib_Node__newindex},
    {"__tostring", mysimplelib_Node__tostring},
    {"__gc", mysimplelib_Node__gc}, // Add GC hook
    {NULL, NULL}
};

// --- End Metatable for struct Node Handle ---

// --- Metatable for struct Buffer Handle (apic.meta.mysimplelib.Buffer) ---

// Helper to safely get C pointer from handle table
static struct Buffer* mysimplelib_Buffer___apic_get_ptr(lua_State *L, const char* meta_name) {
    // Assumes arg 1 is the handle table already validated
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) {
        lua_pop(L, 1);
        luaL_error(L, "Handle table for %s missing or invalid '_id' field", meta_name);
        return NULL; // Should not be reached
    }
    struct Buffer* ptr = (struct Buffer*)lua_touserdata(L, -1);
    lua_pop(L, 1);
    if (ptr == NULL) {
        luaL_error(L, "Handle table for %s '_id' points to NULL", meta_name);
        // return NULL; // Error throws
    }
    return ptr;
}

static int mysimplelib_Buffer__index(lua_State *L) {
    // Arg 1: handle table, Arg 2: key
    const char* key = luaL_checkstring(L, 2);
    struct Buffer* self = mysimplelib_Buffer___apic_get_ptr(L, "apic.meta.mysimplelib.Buffer"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "data") == 0) {
        luaL_error(L, "Direct access to array field 'data' not implemented.");
        return 1;
    }
    if (strcmp(key, "size") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->size));
        return 1;
    }

    // Fallback: Check for methods in metatable
    lua_getmetatable(L, 1);
    lua_pushvalue(L, 2);
    lua_rawget(L, -2);
    lua_remove(L, -2);
    if (!lua_isnil(L, -1)) {
        return 1; // Return method
    } else {
        return luaL_error(L, "No such field or method '%s' in struct %s handle", key, "Buffer", "Buffer");
    }
}

static int mysimplelib_Buffer__newindex(lua_State *L) {
    // Arg 1: handle table, Arg 2: key, Arg 3: value
    const char* key = luaL_checkstring(L, 2);
    struct Buffer* self = mysimplelib_Buffer___apic_get_ptr(L, "apic.meta.mysimplelib.Buffer"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "data") == 0) {
        return luaL_error(L, "Direct assignment to array field 'data' not implemented.");
        return 0; // Assignment successful
    }
    if (strcmp(key, "size") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->size = new_value_size;
        return 0; // Assignment successful
    }

    return luaL_error(L, "No such field '%s' in struct %s handle to assign to", key, "Buffer", "Buffer");
}

static int mysimplelib_Buffer__tostring(lua_State *L) {
    // Arg 1: handle table
    struct Buffer* self = mysimplelib_Buffer___apic_get_ptr(L, "apic.meta.mysimplelib.Buffer"); // Get C pointer
    if (!self) { lua_pushstring(L, "Invalid handle"); return 1; } // Handle NULL case gracefully?
    lua_pushfstring(L, "struct Buffer Handle: %p", (void*)self);
    return 1;
}

// User must define Buffer_release( struct Buffer* obj ) if GC cleanup is needed.
// Example: void Buffer_release(struct Buffer* obj) { printf("Releasing Buffer %p\n", (void*)obj); free(obj); }
// extern void Buffer_release(struct Buffer* obj); // Weak link? Or just call and let linker find it.

static int mysimplelib_Buffer__gc(lua_State *L) {
    // Arg 1: handle table being collected
    printf("GC triggered for Buffer handle.\n"); // Debug
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) == LUA_TLIGHTUSERDATA) {
        struct Buffer* ptr = (struct Buffer*)lua_touserdata(L, -1);
        lua_pop(L, 1);
        if (ptr != NULL) {
            printf("  >> GC: C Pointer is %p\n", (void*)ptr);//mg:Buffer
            // --- Call user-defined C cleanup function --- 
            // Buffer_release(ptr); // Uncomment this line or provide your cleanup call 
            printf("  >> GC: Object cleanup function 'Buffer_release' should be called here.\n");
            // Important: Set handle's _id to NULL after cleanup to prevent double-free/use-after-free
            lua_pushnil(L);
            lua_setfield(L, 1, "_id");
        } else {
             printf("  >> GC: C Pointer was NULL.\n");
        }
    } else {
        printf("  >> GC: Handle table '_id' not lightuserdata!\n");
        lua_pop(L, 1);
    }
    return 0;
}

static const luaL_Reg mysimplelib_Buffer_meta[] = {
    {"__index", mysimplelib_Buffer__index},
    {"__newindex", mysimplelib_Buffer__newindex},
    {"__tostring", mysimplelib_Buffer__tostring},
    {"__gc", mysimplelib_Buffer__gc}, // Add GC hook
    {NULL, NULL}
};

// --- End Metatable for struct Buffer Handle ---

// --- Metatable for struct Matrix Handle (apic.meta.mysimplelib.Matrix) ---

// Helper to safely get C pointer from handle table
static struct Matrix* mysimplelib_Matrix___apic_get_ptr(lua_State *L, const char* meta_name) {
    // Assumes arg 1 is the handle table already validated
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) {
        lua_pop(L, 1);
        luaL_error(L, "Handle table for %s missing or invalid '_id' field", meta_name);
        return NULL; // Should not be reached
    }
    struct Matrix* ptr = (struct Matrix*)lua_touserdata(L, -1);
    lua_pop(L, 1);
    if (ptr == NULL) {
        luaL_error(L, "Handle table for %s '_id' points to NULL", meta_name);
        // return NULL; // Error throws
    }
    return ptr;
}

static int mysimplelib_Matrix__index(lua_State *L) {
    // Arg 1: handle table, Arg 2: key
    const char* key = luaL_checkstring(L, 2);
    struct Matrix* self = mysimplelib_Matrix___apic_get_ptr(L, "apic.meta.mysimplelib.Matrix"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "values") == 0) {
        luaL_error(L, "Direct access to array field 'values' not implemented.");
        return 1;
    }
    if (strcmp(key, "rows") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->rows));
        return 1;
    }
    if (strcmp(key, "cols") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->cols));
        return 1;
    }

    // Fallback: Check for methods in metatable
    lua_getmetatable(L, 1);
    lua_pushvalue(L, 2);
    lua_rawget(L, -2);
    lua_remove(L, -2);
    if (!lua_isnil(L, -1)) {
        return 1; // Return method
    } else {
        return luaL_error(L, "No such field or method '%s' in struct %s handle", key, "Matrix", "Matrix");
    }
}

static int mysimplelib_Matrix__newindex(lua_State *L) {
    // Arg 1: handle table, Arg 2: key, Arg 3: value
    const char* key = luaL_checkstring(L, 2);
    struct Matrix* self = mysimplelib_Matrix___apic_get_ptr(L, "apic.meta.mysimplelib.Matrix"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    if (strcmp(key, "values") == 0) {
        return luaL_error(L, "Direct assignment to array field 'values' not implemented.");
        return 0; // Assignment successful
    }
    if (strcmp(key, "rows") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->rows = new_value_rows;
        return 0; // Assignment successful
    }
    if (strcmp(key, "cols") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->cols = new_value_cols;
        return 0; // Assignment successful
    }

    return luaL_error(L, "No such field '%s' in struct %s handle to assign to", key, "Matrix", "Matrix");
}

static int mysimplelib_Matrix__tostring(lua_State *L) {
    // Arg 1: handle table
    struct Matrix* self = mysimplelib_Matrix___apic_get_ptr(L, "apic.meta.mysimplelib.Matrix"); // Get C pointer
    if (!self) { lua_pushstring(L, "Invalid handle"); return 1; } // Handle NULL case gracefully?
    lua_pushfstring(L, "struct Matrix Handle: %p", (void*)self);
    return 1;
}

// User must define Matrix_release( struct Matrix* obj ) if GC cleanup is needed.
// Example: void Matrix_release(struct Matrix* obj) { printf("Releasing Matrix %p\n", (void*)obj); free(obj); }
// extern void Matrix_release(struct Matrix* obj); // Weak link? Or just call and let linker find it.

static int mysimplelib_Matrix__gc(lua_State *L) {
    // Arg 1: handle table being collected
    printf("GC triggered for Matrix handle.\n"); // Debug
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) == LUA_TLIGHTUSERDATA) {
        struct Matrix* ptr = (struct Matrix*)lua_touserdata(L, -1);
        lua_pop(L, 1);
        if (ptr != NULL) {
            printf("  >> GC: C Pointer is %p\n", (void*)ptr);//mg:Matrix
            // --- Call user-defined C cleanup function --- 
            // Matrix_release(ptr); // Uncomment this line or provide your cleanup call 
            printf("  >> GC: Object cleanup function 'Matrix_release' should be called here.\n");
            // Important: Set handle's _id to NULL after cleanup to prevent double-free/use-after-free
            lua_pushnil(L);
            lua_setfield(L, 1, "_id");
        } else {
             printf("  >> GC: C Pointer was NULL.\n");
        }
    } else {
        printf("  >> GC: Handle table '_id' not lightuserdata!\n");
        lua_pop(L, 1);
    }
    return 0;
}

static const luaL_Reg mysimplelib_Matrix_meta[] = {
    {"__index", mysimplelib_Matrix__index},
    {"__newindex", mysimplelib_Matrix__newindex},
    {"__tostring", mysimplelib_Matrix__tostring},
    {"__gc", mysimplelib_Matrix__gc}, // Add GC hook
    {NULL, NULL}
};

// --- End Metatable for struct Matrix Handle ---

// --- Metatable for union Number Handle (apic.meta.mysimplelib.Number) ---

// Helper to safely get C pointer from handle table
static union Number* mysimplelib_Number___apic_get_ptr(lua_State *L, const char* meta_name) {
    // Assumes arg 1 is the handle table already validated
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) != LUA_TLIGHTUSERDATA) {
        lua_pop(L, 1);
        luaL_error(L, "Handle table for %s missing or invalid '_id' field", meta_name);
        return NULL; // Should not be reached
    }
    union Number* ptr = (union Number*)lua_touserdata(L, -1);
    lua_pop(L, 1);
    if (ptr == NULL) {
        luaL_error(L, "Handle table for %s '_id' points to NULL", meta_name);
        // return NULL; // Error throws
    }
    return ptr;
}

static int mysimplelib_Number__index(lua_State *L) {
    // Arg 1: handle table, Arg 2: key
    const char* key = luaL_checkstring(L, 2);
    union Number* self = mysimplelib_Number___apic_get_ptr(L, "apic.meta.mysimplelib.Number"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    // Reading union fields - Use with caution!
    if (strcmp(key, "i") == 0) {
    lua_pushinteger(L, (lua_Integer)(self->i));
        return 1;
    }
    if (strcmp(key, "f") == 0) {
    lua_pushnumber(L, (lua_Number)(self->f));
        return 1;
    }

    // Fallback: Check for methods in metatable
    lua_getmetatable(L, 1);
    lua_pushvalue(L, 2);
    lua_rawget(L, -2);
    lua_remove(L, -2);
    if (!lua_isnil(L, -1)) {
        return 1; // Return method
    } else {
        return luaL_error(L, "No such field or method '%s' in union %s handle", key, "Number", "Number");
    }
}

static int mysimplelib_Number__newindex(lua_State *L) {
    // Arg 1: handle table, Arg 2: key, Arg 3: value
    const char* key = luaL_checkstring(L, 2);
    union Number* self = mysimplelib_Number___apic_get_ptr(L, "apic.meta.mysimplelib.Number"); // Get C pointer
    if (!self) return 0; // Error handled by helper

    // Assigning union fields - Use with caution!
    if (strcmp(key, "i") == 0) {
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 3, "__newindex");
        self->i = new_value_i;
        return 0; // Assignment successful
    }
    if (strcmp(key, "f") == 0) {
    float new_value_f = (float)luaL_checknumber(L, 3);
        self->f = new_value_f;
        return 0; // Assignment successful
    }

    return luaL_error(L, "No such field '%s' in union %s handle to assign to", key, "Number", "Number");
}

static int mysimplelib_Number__tostring(lua_State *L) {
    // Arg 1: handle table
    union Number* self = mysimplelib_Number___apic_get_ptr(L, "apic.meta.mysimplelib.Number"); // Get C pointer
    if (!self) { lua_pushstring(L, "Invalid handle"); return 1; } // Handle NULL case gracefully?
    lua_pushfstring(L, "union Number Handle: %p", (void*)self);
    return 1;
}

// User must define Number_release( union Number* obj ) if GC cleanup is needed.
// Example: void Number_release(union Number* obj) { printf("Releasing Number %p\n", (void*)obj); free(obj); }
// extern void Number_release(union Number* obj); // Weak link? Or just call and let linker find it.

static int mysimplelib_Number__gc(lua_State *L) {
    // Arg 1: handle table being collected
    printf("GC triggered for Number handle.\n"); // Debug
    lua_getfield(L, 1, "_id");
    if (lua_type(L, -1) == LUA_TLIGHTUSERDATA) {
        union Number* ptr = (union Number*)lua_touserdata(L, -1);
        lua_pop(L, 1);
        if (ptr != NULL) {
            printf("  >> GC: C Pointer is %p\n", (void*)ptr);//mg:Number
            // --- Call user-defined C cleanup function --- 
            // Number_release(ptr); // Uncomment this line or provide your cleanup call 
            printf("  >> GC: Object cleanup function 'Number_release' should be called here.\n");
            // Important: Set handle's _id to NULL after cleanup to prevent double-free/use-after-free
            lua_pushnil(L);
            lua_setfield(L, 1, "_id");
        } else {
             printf("  >> GC: C Pointer was NULL.\n");
        }
    } else {
        printf("  >> GC: Handle table '_id' not lightuserdata!\n");
        lua_pop(L, 1);
    }
    return 0;
}

static const luaL_Reg mysimplelib_Number_meta[] = {
    {"__index", mysimplelib_Number__index},
    {"__newindex", mysimplelib_Number__newindex},
    {"__tostring", mysimplelib_Number__tostring},
    {"__gc", mysimplelib_Number__gc}, // Add GC hook
    {NULL, NULL}
};

// --- End Metatable for union Number Handle ---

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
//               END METATABLE DEFINITIONS
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

// --- Wrapped C Functions ---
// Wrapper for add_mixed
static int lua_add_mixed(lua_State *L) {
    int n_args = lua_gettop(L);
    if (n_args != 2) { return luaL_error(L, "Function 'add_mixed' expects 2 arguments, got %d", n_args); }

    // Arg 1: a
    luaL_error(L, "Unsupported primitive type '%s' for argument %d in %s", "int", 1, "add_mixed");
    // Arg 2: b
    float arg_b = (float)luaL_checknumber(L, 2);

    // Call C function 'add_mixed'
    int c_result = add_mixed(arg_a, arg_b);

    lua_pushinteger(L, (lua_Integer)(c_result));
    return 1;
}

// --- End Wrapped C Functions ---

// --- Lua Module Function Registration Data ---
static const struct luaL_Reg mysimplelib_funcs[] = {
    {"add_mixed", lua_add_mixed},
    {NULL, NULL} // Sentinel
};

// --- Enum Registration Function ---
static void register_enums_mysimplelib(lua_State *L) {
}

// --- Metatable Registration Function ---
static void register_metatables_mysimplelib(lua_State *L) {
    // Register handle metatable for struct Vec2I
    luaL_newmetatable(L, "apic.meta.mysimplelib.Vec2I"); // Create if not exists
    luaL_register(L, NULL, mysimplelib_Vec2I_meta); // Register methods (__index etc)
    lua_pop(L, 1); // Pop metatable

    // Register handle metatable for struct Vec3I
    luaL_newmetatable(L, "apic.meta.mysimplelib.Vec3I"); // Create if not exists
    luaL_register(L, NULL, mysimplelib_Vec3I_meta); // Register methods (__index etc)
    lua_pop(L, 1); // Pop metatable

    // Register handle metatable for struct Calculator
    luaL_newmetatable(L, "apic.meta.mysimplelib.Calculator"); // Create if not exists
    luaL_register(L, NULL, mysimplelib_Calculator_meta); // Register methods (__index etc)
    lua_pop(L, 1); // Pop metatable

    // Register handle metatable for struct Node
    luaL_newmetatable(L, "apic.meta.mysimplelib.Node"); // Create if not exists
    luaL_register(L, NULL, mysimplelib_Node_meta); // Register methods (__index etc)
    lua_pop(L, 1); // Pop metatable

    // Register handle metatable for struct Buffer
    luaL_newmetatable(L, "apic.meta.mysimplelib.Buffer"); // Create if not exists
    luaL_register(L, NULL, mysimplelib_Buffer_meta); // Register methods (__index etc)
    lua_pop(L, 1); // Pop metatable

    // Register handle metatable for struct Matrix
    luaL_newmetatable(L, "apic.meta.mysimplelib.Matrix"); // Create if not exists
    luaL_register(L, NULL, mysimplelib_Matrix_meta); // Register methods (__index etc)
    lua_pop(L, 1); // Pop metatable

    // Register handle metatable for union Number
    luaL_newmetatable(L, "apic.meta.mysimplelib.Number");
    luaL_register(L, NULL, mysimplelib_Number_meta);
    lua_pop(L, 1);

}

// --- Module Entry Point ---
#ifdef __cplusplus
extern "C" {
#endif
LUALIB_API int luaopen_mysimplelib(lua_State *L);
#ifdef __cplusplus
}
#endif

LUALIB_API int luaopen_mysimplelib(lua_State *L) {
    luaL_register(L, "mysimplelib", mysimplelib_funcs);

    register_metatables_mysimplelib(L);

    register_enums_mysimplelib(L);

    lua_pushstring(L, "Example exports with full documentation support"); lua_setfield(L, -2, "_DOC");
    return 1; // Return module table
}
// --- End Module Entry Point ---
